import 'dart:collection';
import 'dart:math' as math;

import 'model.dart';

/// Represents edge distances in the layout engine without Flutter dependencies.
final class TreemapInsets {
  const TreemapInsets.fromLTRB(this.left, this.top, this.right, this.bottom);
  const TreemapInsets.all(double value)
    : left = value,
      top = value,
      right = value,
      bottom = value;
  const TreemapInsets.symmetric({double horizontal = 0, double vertical = 0})
    : left = horizontal,
      right = horizontal,
      top = vertical,
      bottom = vertical;

  static const zero = TreemapInsets.all(0);

  final double left;
  final double top;
  final double right;
  final double bottom;

  double get horizontal => left + right;
  double get vertical => top + bottom;
  bool get isFinite =>
      left.isFinite && top.isFinite && right.isFinite && bottom.isFinite;
  bool get isNonNegative => left >= 0 && top >= 0 && right >= 0 && bottom >= 0;

  @override
  bool operator ==(Object other) =>
      other is TreemapInsets &&
      left == other.left &&
      top == other.top &&
      right == other.right &&
      bottom == other.bottom;

  @override
  int get hashCode => Object.hash(left, top, right, bottom);

  @override
  String toString() => 'TreemapInsets($left, $top, $right, $bottom)';
}

/// Represents an immutable axis-aligned rectangle in treemap coordinates.
final class TreemapBounds {
  const TreemapBounds.fromLTWH(this.left, this.top, this.width, this.height);
  const TreemapBounds.zero() : this.fromLTWH(0, 0, 0, 0);

  final double left;
  final double top;
  final double width;
  final double height;

  double get right => left + width;
  double get bottom => top + height;
  double get area => math.max(0, width) * math.max(0, height);
  double get centerX => left + width / 2;
  double get centerY => top + height / 2;
  bool get isEmpty => width <= 0 || height <= 0;
  bool get isFinite =>
      left.isFinite && top.isFinite && width.isFinite && height.isFinite;

  bool contains(double x, double y, {double padding = 0}) {
    return x >= left - padding &&
        x <= right + padding &&
        y >= top - padding &&
        y <= bottom + padding;
  }

  TreemapBounds inset(TreemapInsets insets) {
    final nextWidth = math.max(0.0, width - insets.horizontal);
    final nextHeight = math.max(0.0, height - insets.vertical);
    return TreemapBounds.fromLTWH(
      left + math.min(width, insets.left),
      top + math.min(height, insets.top),
      nextWidth,
      nextHeight,
    );
  }

  TreemapBounds inflate(double value) => TreemapBounds.fromLTWH(
    left - value,
    top - value,
    math.max(0, width + value * 2),
    math.max(0, height + value * 2),
  );

  TreemapBounds clampTo(TreemapBounds container) {
    final nextLeft = left.clamp(container.left, container.right).toDouble();
    final nextTop = top.clamp(container.top, container.bottom).toDouble();
    final nextRight = right.clamp(nextLeft, container.right).toDouble();
    final nextBottom = bottom.clamp(nextTop, container.bottom).toDouble();
    return TreemapBounds.fromLTWH(
      nextLeft,
      nextTop,
      nextRight - nextLeft,
      nextBottom - nextTop,
    );
  }

  bool overlaps(TreemapBounds other, {double tolerance = 1e-9}) {
    final overlapWidth =
        math.min(right, other.right) - math.max(left, other.left);
    final overlapHeight =
        math.min(bottom, other.bottom) - math.max(top, other.top);
    return overlapWidth > tolerance && overlapHeight > tolerance;
  }

  static TreemapBounds lerp(TreemapBounds a, TreemapBounds b, double t) {
    return TreemapBounds.fromLTWH(
      a.left + (b.left - a.left) * t,
      a.top + (b.top - a.top) * t,
      a.width + (b.width - a.width) * t,
      a.height + (b.height - a.height) * t,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is TreemapBounds &&
      left == other.left &&
      top == other.top &&
      width == other.width &&
      height == other.height;

  @override
  int get hashCode => Object.hash(left, top, width, height);

  @override
  String toString() => 'TreemapBounds($left, $top, $width, $height)';
}

/// Identifies whether rendered geometry came from data or aggregation.
enum TreemapGeometryKind {
  /// Geometry corresponding directly to a source [TreemapNode].
  source,

  /// Geometry generated by combining undersized source siblings.
  aggregate,
}

/// Describes one laid-out source or aggregate node.
final class TreemapGeometryNode<K> {
  TreemapGeometryNode({
    required this.key,
    required this.bounds,
    required this.weight,
    required this.depth,
    required this.kind,
    required this.label,
    required this.parentKey,
    required this.opacity,
    this.node,
    Iterable<TreemapNode<K>> aggregateMembers = const [],
  }) : aggregateMembers = List.unmodifiable(aggregateMembers);

  final TreemapKey<K> key;
  final TreemapNode<K>? node;
  final TreemapBounds bounds;
  final double weight;
  final int depth;
  final TreemapGeometryKind kind;
  final String? label;
  final TreemapKey<K>? parentKey;
  final double opacity;
  final List<TreemapNode<K>> aggregateMembers;

  bool get isAggregate => kind == TreemapGeometryKind.aggregate;
  bool get hasChildren => isAggregate
      ? aggregateMembers.isNotEmpty
      : (node?.children.isNotEmpty ?? false);

  TreemapGeometryNode<K> copyWith({
    TreemapBounds? bounds,
    double? opacity,
    TreemapKey<K>? parentKey,
  }) => TreemapGeometryNode<K>(
    key: key,
    node: node,
    bounds: bounds ?? this.bounds,
    weight: weight,
    depth: depth,
    kind: kind,
    label: label,
    parentKey: parentKey ?? this.parentKey,
    opacity: opacity ?? this.opacity,
    aggregateMembers: aggregateMembers,
  );
}

/// Identifies one branch in the path from the root to the current focus.
final class TreemapPathEntry<K> {
  const TreemapPathEntry({required this.key, this.label, required this.depth});

  final TreemapKey<K> key;
  final String? label;
  final int depth;
}

/// Stores the complete immutable output of one layout pass.
final class TreemapGeometrySnapshot<K> {
  TreemapGeometrySnapshot({
    required this.viewport,
    required Iterable<TreemapGeometryNode<K>> nodes,
    required Iterable<TreemapPathEntry<K>> path,
    required this.focusKey,
    this.revision = 0,
  }) : nodes = List.unmodifiable(nodes),
       path = List.unmodifiable(path),
       index = UnmodifiableMapView({for (final node in nodes) node.key: node});

  factory TreemapGeometrySnapshot.empty(TreemapBounds viewport) =>
      TreemapGeometrySnapshot<K>(
        viewport: viewport,
        nodes: const [],
        path: const [],
        focusKey: null,
      );

  final TreemapBounds viewport;
  final List<TreemapGeometryNode<K>> nodes;
  final Map<TreemapKey<K>, TreemapGeometryNode<K>> index;
  final List<TreemapPathEntry<K>> path;
  final TreemapKey<K>? focusKey;
  final int revision;

  String toStringDeep({int maximumNodes = 20}) {
    final buffer = StringBuffer(
      'TreemapGeometrySnapshot(revision: $revision, focus: $focusKey, '
      'viewport: $viewport, nodes: ${nodes.length})',
    );
    for (final node in nodes.take(maximumNodes)) {
      buffer.write(
        '\n  ${node.key} depth=${node.depth} weight=${node.weight} '
        'bounds=${node.bounds} opacity=${node.opacity}',
      );
    }
    if (nodes.length > maximumNodes) {
      buffer.write('\n  … ${nodes.length - maximumNodes} more nodes');
    }
    return buffer.toString();
  }

  @override
  String toString() =>
      'TreemapGeometrySnapshot(revision: $revision, nodes: ${nodes.length}, '
      'focus: $focusKey)';

  Iterable<TreemapGeometryNode<K>> get visibleNodes =>
      nodes.where((node) => node.opacity > 0 && !node.bounds.isEmpty);

  TreemapGeometryNode<K>? hitTest(double x, double y, {double padding = 0}) {
    TreemapGeometryNode<K>? match;
    for (final node in visibleNodes) {
      if (node.bounds.contains(x, y, padding: padding) &&
          (match == null || node.depth >= match.depth)) {
        match = node;
      }
    }
    return match;
  }
}

/// Categorizes an invariant violation found in a geometry snapshot.
enum TreemapGeometryIssueCode {
  /// At least one coordinate or dimension is not finite.
  nonFinite,

  /// A rectangle has a negative width or height.
  negativeSize,

  /// A node rectangle extends outside its parent rectangle or viewport.
  outsideParent,

  /// Two sibling rectangles occupy the same positive-area region.
  overlap,

  /// More than one geometry node uses the same key.
  duplicateKey,

  /// A node refers to a parent absent from the snapshot.
  invalidParent,
}

/// Describes one geometry diagnostic with an optional affected node key.
final class TreemapGeometryIssue<K> {
  const TreemapGeometryIssue(this.code, this.message, {this.key});
  final TreemapGeometryIssueCode code;
  final TreemapKey<K>? key;
  final String message;
}

/// Validates snapshot containment, identity, dimensions, and sibling overlap.
abstract final class TreemapGeometryDiagnostics {
  static List<TreemapGeometryIssue<K>> validate<K>(
    TreemapGeometrySnapshot<K> snapshot, {
    double tolerance = 1e-7,
  }) {
    final issues = <TreemapGeometryIssue<K>>[];
    final keys = <TreemapKey<K>>{};
    final siblings = <TreemapKey<K>?, List<TreemapGeometryNode<K>>>{};
    for (final node in snapshot.nodes) {
      if (!keys.add(node.key)) {
        issues.add(
          TreemapGeometryIssue(
            TreemapGeometryIssueCode.duplicateKey,
            'Geometry key occurs more than once.',
            key: node.key,
          ),
        );
      }
      if (!node.bounds.isFinite) {
        issues.add(
          TreemapGeometryIssue(
            TreemapGeometryIssueCode.nonFinite,
            'Bounds contain a non-finite coordinate.',
            key: node.key,
          ),
        );
      }
      if (node.bounds.width < -tolerance || node.bounds.height < -tolerance) {
        issues.add(
          TreemapGeometryIssue(
            TreemapGeometryIssueCode.negativeSize,
            'Bounds contain a negative dimension.',
            key: node.key,
          ),
        );
      }
      final parent = node.parentKey == null
          ? null
          : snapshot.index[node.parentKey];
      final container = parent?.bounds ?? snapshot.viewport;
      if (node.bounds.left < container.left - tolerance ||
          node.bounds.top < container.top - tolerance ||
          node.bounds.right > container.right + tolerance ||
          node.bounds.bottom > container.bottom + tolerance) {
        issues.add(
          TreemapGeometryIssue(
            TreemapGeometryIssueCode.outsideParent,
            'Bounds escape their parent or viewport.',
            key: node.key,
          ),
        );
      }
      if (node.parentKey != null && parent == null) {
        issues.add(
          TreemapGeometryIssue(
            TreemapGeometryIssueCode.invalidParent,
            'Parent key is absent from the snapshot.',
            key: node.key,
          ),
        );
      }
      siblings.putIfAbsent(node.parentKey, () => []).add(node);
    }

    for (final group in siblings.values) {
      for (var i = 0; i < group.length; i++) {
        for (var j = i + 1; j < group.length; j++) {
          if (group[i].bounds.overlaps(group[j].bounds, tolerance: tolerance)) {
            issues.add(
              TreemapGeometryIssue(
                TreemapGeometryIssueCode.overlap,
                '${group[i].key} overlaps ${group[j].key}.',
                key: group[i].key,
              ),
            );
          }
        }
      }
    }
    return List.unmodifiable(issues);
  }
}

/// Interpolates keyed nodes between two geometry snapshots.
abstract final class TreemapGeometryTransition {
  static TreemapGeometrySnapshot<K> lerp<K>(
    TreemapGeometrySnapshot<K> from,
    TreemapGeometrySnapshot<K> to,
    double t,
  ) {
    if (t <= 0) return from;
    if (t >= 1) return to;
    final keys = <TreemapKey<K>>{...from.index.keys, ...to.index.keys};
    final nodes = <TreemapGeometryNode<K>>[];
    for (final key in keys) {
      final a = from.index[key];
      final b = to.index[key];
      if (a != null && b != null) {
        nodes.add(
          b.copyWith(
            bounds: TreemapBounds.lerp(a.bounds, b.bounds, t),
            opacity: a.opacity + (b.opacity - a.opacity) * t,
          ),
        );
      } else if (b != null) {
        final anchor = _anchorFor(b, from) ?? b.bounds;
        nodes.add(
          b.copyWith(
            bounds: TreemapBounds.lerp(_collapsed(anchor), b.bounds, t),
            opacity: b.opacity * t,
          ),
        );
      } else if (a != null) {
        final anchor = _anchorFor(a, to) ?? a.bounds;
        nodes.add(
          a.copyWith(
            bounds: TreemapBounds.lerp(a.bounds, _collapsed(anchor), t),
            opacity: a.opacity * (1 - t),
          ),
        );
      }
    }
    return TreemapGeometrySnapshot<K>(
      viewport: TreemapBounds.lerp(from.viewport, to.viewport, t),
      nodes: nodes,
      path: t < .5 ? from.path : to.path,
      focusKey: t < .5 ? from.focusKey : to.focusKey,
      revision: to.revision,
    );
  }

  static TreemapBounds? _anchorFor<K>(
    TreemapGeometryNode<K> node,
    TreemapGeometrySnapshot<K> snapshot,
  ) => node.parentKey == null
      ? snapshot.viewport
      : snapshot.index[node.parentKey]?.bounds;

  static TreemapBounds _collapsed(TreemapBounds bounds) =>
      TreemapBounds.fromLTWH(bounds.centerX, bounds.centerY, 0, 0);
}
